## Documentation: http://docs.travis-ci.com/user/languages/julia/
language: julia
os:
  - linux
  - osx
julia:
  - 0.6
  - nightly
notifications:
  email: false
git:
  depth: 99999999

#matrix:
allow_failures:
  - julia: nightly

## uncomment the following lines to override the default test script
script:
  - julia -e 'using Pkg; Pkg.add("Test"); Pkg.clone(pwd()); Pkg.build("AuditoryStimuli"); Pkg.test("AuditoryStimuli"; coverage=true)'
after_success:
  # push coverage results to Codecov
  - julia -e 'cd(Pkg.dir("AuditoryStimuli")); Pkg.add("Coverage"); using Coverage; Codecov.submit(Codecov.process_folder())'
